# Generated by Django 3.0.6 on 2020-06-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='price',
        ),
    ]
