# Generated by Django 3.0.6 on 2020-06-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200619_1059'),
        ('basket', '0002_remove_basketitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Colour'),
        ),
    ]
