# Generated by Django 3.0.6 on 2020-06-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_value', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=254)),
                ('season', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='friendly_name',
            new_name='display_name',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField()),
                ('product_colors', models.ManyToManyField(to='products.Colour')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
        ),
    ]
