# Generated by Django 3.0.6 on 2020-06-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200609_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='display_name',
        ),
    ]
